// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjIIyO0pefgs2y3q6SbaGKg8Ly4kP-0eU',
    appId: '1:533872273646:web:68ae7e960f165553d5abff',
    messagingSenderId: '533872273646',
    projectId: 'notifications-learn-try-app',
    authDomain: 'notifications-learn-try-app.firebaseapp.com',
    storageBucket: 'notifications-learn-try-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVv6ycwXCCFPEM0ZXgoE2eovWAu8-85zs',
    appId: '1:533872273646:android:8d893532277b9a3bd5abff',
    messagingSenderId: '533872273646',
    projectId: 'notifications-learn-try-app',
    storageBucket: 'notifications-learn-try-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj1VbLtkOkdnXID8fnzIpbZ9d4AogdbUw',
    appId: '1:533872273646:ios:909e422d44f4292ad5abff',
    messagingSenderId: '533872273646',
    projectId: 'notifications-learn-try-app',
    storageBucket: 'notifications-learn-try-app.appspot.com',
    iosClientId: '533872273646-38q9rm6ssucssd0jor46f5tnr9sr8rha.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj1VbLtkOkdnXID8fnzIpbZ9d4AogdbUw',
    appId: '1:533872273646:ios:909e422d44f4292ad5abff',
    messagingSenderId: '533872273646',
    projectId: 'notifications-learn-try-app',
    storageBucket: 'notifications-learn-try-app.appspot.com',
    iosClientId: '533872273646-38q9rm6ssucssd0jor46f5tnr9sr8rha.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationsApp',
  );
}
